#!/bin/python3

import math
import os
import random
import re
import sys

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#maxvalue
def evenFibonacci(maxValue = 4000000):
    seq = [1, 2]
    i = 2
    total = 2
    while((seq[i-2] + seq[i-1])<maxValue):
        nextNum = seq[i-2] + seq[i-1]
        seq.append(nextNum)
        if(nextNum%2==0):
            total+=nextNum
        i+=1

    return total

print(evenFibonacci())
#returns 4613732 - correct!
